image: centos:7

only:
  - merge_requests
except:
     variables:
       - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "develop"

variables:
  GENIE_VERSION: "3.0.6"
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - echo "-- Working Directory"
  - pwd
  - echo "-- Directory Contents"
  - ls
  - echo "-- Setup Spack"
  - export SPACK_ROOT=$(pwd)/spack
  - ./install.sh
  - . spack/share/spack/setup-env.sh
  - echo "-- Environment Variables"
  - env

build_genie:
  stage: build
  timeout: 1d
  script:
    - spack install genie@${GENIE_VERSION}+test+vleextension+validationtools+t2k+fnal+atmo+nucleondecay+masterclass
  parallel:
    matrix:
      - GENIE_VERSION: ["3.0.6", "2.12.10", "2.8.6"]

